// frontend-react/src/components/SideMenu.jsx
import React, { Component } from 'react'
import { Link } from "react-router-dom";

export default class SideMenu extends Component {

  constructor(props) {
    super(props)
    this.state = {
      open: false,
      runAnimation: false
    }
  }

  toggleOpen = () => {
    this.setState({open: !this.state.open, runAnimation: true})
  }

  render() {
    return (
      <div className="menu-container">
        <div className="open-menu-button">
          <i className="material-icons" onClick={() => this.toggleOpen()}>menu</i>
        </div>
        {this.renderMenu()}
        {this.renderOverlay()}
      </div>
    )
  }

  renderOverlay = () => {
    const overlayClassName = this.state.open ? "invis-overlay--active" : ""
    return <div className={`invis-overlay ${overlayClassName}`} onClick={() => this.toggleOpen()}></div>
  }

  renderMenu = () => {
    const { toggleOpen, state: { open, runAnimation } } = this
    const menuClassName = ( open && runAnimation ) ? "side-menu--open" : ( !open && runAnimation ) ? "side-menu--closed" : ""
    const homeLinkClassName = ( window.location.pathname === "/" ) ? "link--active" : ""
    const aboutLinkClassName = ( window.location.pathname === "/about" ) ? "link--active" : ""

    return (
      <div className={`side-menu ${menuClassName}`}>

        <div className="side-menu__item close-menu-button">
          <i className="material-icons" onClick={() => toggleOpen()}>arrow_back</i>
          <h2 onClick={() => toggleOpen()}>Close menu</h2>
        </div>
        
        <nav className="side-menu__item menu-nav">
          <ul className="menu-nav__list">
            <li className="menu-nav__list__item" onClick={() => toggleOpen()}>
              <Link to="/">
                <i className={`material-icons ${homeLinkClassName}`}>home</i>
              </Link>
            </li>
            <li className="menu-nav__list__item" onClick={() => toggleOpen()}>
              <Link to="/about">
                <i className={`material-icons ${aboutLinkClassName}`}>help_outline</i>
              </Link>
            </li>
          </ul>
        </nav>

      </div>
    )
  }

}

// frontend-vue/src/components/SideMenu.vue
<template>
  <div class="menu-container">
    <div class="open-menu-button">
      <i class="material-icons" @click="toggleOpen">menu</i>
    </div>

    <div  class="side-menu"
          :class="{
            'side-menu--closed': (!open && runAnimation),
            'side-menu--open': (open && runAnimation)
          }"
    >

      <div class="side-menu__item close-menu-button">
        <i class="material-icons" @click="toggleOpen">arrow_back</i>
        <h2 @click="toggleOpen">Close menu</h2>
      </div>
      
      <nav class="side-menu__item menu-nav">
        <ul class="menu-nav__list">
          <li class="menu-nav__list__item">
            <router-link to="/">
              <i  class="material-icons"
                  :class="{'link--active': (this.$route.path === '/')}"
                  @click="toggleOpen"
              >
                home
              </i>
            </router-link>
          </li>
          <li class="menu-nav__list__item">
            <router-link  to="/about">
              <i  class="material-icons"
                  :class="{'link--active': (this.$route.path === '/about')}"
                  @click="toggleOpen"
              >
                help_outline
              </i>
            </router-link>
          </li>
        </ul>
      </nav>

    </div>

    <div class="invis-overlay" :class="{'invis-overlay--active': open }" @click="toggleOpen"></div>

  </div>
</template>

<script>
export default {
  data() {
    return {
      open: false,
      runAnimation: false
    }
  },
  methods: {
    toggleOpen: function () {
      this.open = !this.open
      this.runAnimation = true
    }
  },
}
</script>
