// frontend-vue/src/App.vue
<template>
  <div class="app">
    <!-- <header>
      <router-link to="/">Home</router-link>
      <router-link to="/about">About</router-link>
    </header> -->
    <Header></Header>
    <div class="views">
      <router-view/>
    </div>
  </div>
</template>

<script>
import Header from './components/Header.vue'

export default {
  components: {
    Header,
  }
}
</script>

<style lang="scss">
@import './index.css'
</style>

// frontend-react/src/App.jsx
import React, { Component } from 'react'
import { BrowserRouter as Router, Switch, Route, Link } from "react-router-dom";
import Home from './views/Home';
import About from './views/About';
import './App.css';

export default class App extends Component {
  render() {
    return (
      <Router>
        <div className="app">
          <header>
            <Link to="/">Home</Link>
            <Link to="/about">About</Link>
          </header>
          <div className="views">
            <Switch>
              <Route path="/" exact component={Home}/>
              <Route path="/about" component={About}/>
            </Switch>
          </div>
        </div>
      </Router>
    )
  }
}
